name: Bump Homebrew Cask

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag'
        required: true
      sha:
        description: 'SHA'
        required: true

jobs:
  bump-cask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Homebrew cask
        uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          tap: dail8859/homebrew-notepadnext
          cask: Casks/notepadnext.rb
          tag: ${{ github.event.inputs.ref || github.event.release.tag_name }}
          revision: ${{ github.event.inputs.sha || github.event.release.target_commitish }}
